# config file for circleci
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stable
    steps:
      - checkout
      - run:
          name: configure
          command: configure
      - run:
          name: make clean tests
          command: make clean tests
      - run:
          name: run tests
          command: make light heavy
