# config file for circleci
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stable
    steps:
      - checkout
      - run:
          name: configure
          command: ./configure
      - run:
          name: make
          command: make clean all tests
      - run:
          name: run utility
          command: ./dmalloc
      - run:
          name: run tests
          command: make light heavy
